config/urls.py
from django.conf.urls import url, include, handler404, handler500
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from project.polls import views
# import the verbs to ensure it is registered
from project.polls.verbs import Vote, Like, Share, UpdateProfile, FollowVerb

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('project.polls.urls',namespace='polls',
        app_name='polls')),
    url(r'^account/', include('project.account.urls', namespace='account',
        app_name='account')),
    url(r'^$', views.index, name='index'), # homepage
    # url(r'^index_graph/$', views.index_graph, name='index_graph'),
    url(r'^privacy-policy/$', views.privacy_policy, name='privacy'),
    url(r'^terms-of-service/$', views.terms_of_service, name='terms'),
    url(r'^help-using-our-services/$', views.help_page, name='help'),
    url(r'^feedback/$', views.feedback_page, name="feedback"),

    #Add social URL
    url(r'^social-auth/', include('social_django.urls', namespace='social')),
]

handler404 = views.error_404
handler500 = views.error_500

project/polls/urls.py
from django.conf.urls import url, include
from project.polls import views

app_name='polls'
urlpatterns = [
    #Browsing
    # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/(?P<slug>[-\w]+)/$',
        views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/(?P<slug>[-\w]+)/results/$',
        views.results, name='results'),
    url(r'^feat/$', views.features, name='features'),
    url(r'^popular/$', views.popular_polls, name='popular'),
    url(r'^recent/$', views.recent_polls, name='recent'),
    url(r'^search/$', views.search_page, name='search'),
    url(r'^list-voters/$', views.get_voters_list, name='voters'),
    url(r'^graphs/$', views.dashboard_graphs, name="graphs"),
    url(r'^([-\w]+)/voted/$', views.voted_polls, name='voted_polls'),
    url(r'^([-\w]+)/liked/$', views.liked_polls, name='liked_polls'),
    url(r'^([-\w]+)/commented/$', views.commented_polls, name='commented_polls'),

    # content management
    url(r'^question/(?P<question_id>[0-9]+)/settings/(?P<poll_type>[-\w]+)/$',
        views.question_settings, name='questionsettings'),
    url(r'remove/poll/(?P<question_id>[0-9]+)/$', views.suspend_poll, name='suspend'),
    url(r'^comments/(?P<question_id>[0-9]+)/$', views.comments, name='comments'),
    # ex: /polls/5/vote/
    url(r'^vote/(?P<question_id>[0-9]+)/$', views.vote, name='vote'),
    url(r'^dashboard/user/([-\w]+)/$', views.dashboard, name='dashboard'),
    url(r'^user/([-\w]+)/$', views.user_page, name='user_page'),
    url(r'^([-\w]+)/save/$', views.question_save, name='save_page'),
    url(r'^edit/(?P<question_id>[0-9]+)/save/$', views.question_edit,
        name='edit_question'),
    url(r'^submit_a_poll/$',views.create_anonymous, name='create'),
    url(r'^like/(?P<question_id>[0-9]+)/$', views.like, name="like"),
    url(r'^new-share/(?P<question_id>[0-9]+)/(?P<poll_type>[-\w]+)/$',
        views.share, name="share"),
    url(r'^share/ranking/$', views.share_ranking, name="share_ranks"),

    # quiz Browsing
    url(r'^quiz/(?P<quiz_id>[0-9]+)/(?P<slug>[-\w]+)/$', views.quiz_detail,
        name='quiz_detail'),
    # quiz content management
    url(r'^([-\w]+)/quiz/presave/$', views.pre_create_quiz, name='pre_save_quiz'),
    url(r'^create/(?P<quiz_id>[0-9]+)/quiz/save/$', views.create_new_quiz,
        name='save_quiz'),
    url(r'^edit/(?P<quiz_id>[0-9]+)/quiz/$', views.edit_quiz, name='edit_quiz'),
    url(r'^quiz_question/edit/(?P<question_id>[0-9]+)/quiz/$',
        views.edit_quiz_question, name='edit_quiz_question'),
    url(r'^quiz_vote/(?P<quiz_id>[0-9]+)/(?P<slug>[-\w]+)/$', views.quiz_vote,
        name='quiz_vote'),

    # Friends
    url(r'^friends/([-\w]+)/$', views.friends_page, name='friends'),
    url(r'^friend/follow/$', views.friend_follow, name='friend_follow'),
    url(r'^friend/invite/$', views.friend_invite, name='friend_invite'),
    url(r'^friend/accept/([-\w]+)/$', views.friend_accept, name='friend_accept'),

    # mail
    url(r'^send_mail/$', views.send_bulk, name='sendmail'),
    url(r'^personal_mail/$', views.one_message, name='personalmail'),

    # feeds management
    url(r'^news_feed/$', views.feeds, name='feeds'),
    url(r'^feed/notifications/$', views.notification, name='notification'),
    url(r'^seen_activity/$', views.mark_as_seen,),

    url(r'^question/(?P<question_id>[0-9]+)/$', views.detail2, name='detail2'),
]

project/polls/views.py
import redis
import json
from django.shortcuts import render, get_object_or_404, render_to_response, redirect
from django.http import Http404, HttpResponseRedirect, HttpResponse, JsonResponse
from .models import *
from .forms import *
from project.account.models import Profile, Group, Invitation, Friendship, User
from project.account.forms import GroupForm, FriendInviteForm, AccountSettingsForm
# helps to avoid race conditions & enable use of | OR and & AND
from django.db.models import F, Q
from django.db.utils import IntegrityError
from django.forms import inlineformset_factory, modelformset_factory
# To including message interfaces
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Applying page numbers
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.signing import Signer, BadSignature
from project.polls.common.decorators import ajax_required
from django.views.decorators.http import require_POST
from datetime import datetime, timedelta, date
from django.utils import timezone
from django.core.mail import EmailMessage
from django.core.mail import send_mail, send_mass_mail
from django.template import Context, loader
from django.conf import settings
# using stream_framework for Notifications
from project.polls.feeds import MyNotificationFeed
from stream_framework.feeds.notification_feed.base import BaseNotificationFeed
from project.polls.feed_managers import manager, notify
from config.tasks import new_vote, invitation_mail

# connect to redis
r = redis.StrictRedis(host=settings.REDIS_HOST,
                      port=settings.REDIS_PORT,
                      db=settings.REDIS_DB)

# GLOBAL CONSTANTS
ITEMS_PER_PAGE = 10

NOW = timezone.now()

# Create your views here.
def privacy_policy(request):
    return render (request,'polls/privacy_policy.html',{
        'head_title': "PollsPortal Privacy Policy",
    })

def terms_of_service(request):
    return render (request,'polls/terms_service.html',{
        'head_title': "Terms of Service",
    })

def help_page(request):
    return render(request,'polls/help.html',
        {
        'head_title': "PollsPortal Help Page"
        }

    )

def feedback_page(request):
    if request.method == 'POST':
        feedback_form = FeedBackForm(data=request.POST) # Post a comment
        if feedback_form.is_valid():
            # Now create a feedback object but not yet saved to database
            new_feedback = feedback_form.save(commit=False)

            new_feedback.user = request.user
            # now save the comment to the database
            new_feedback.save()

            messages.success(request,
              "Message submitted! Thank you."
            )
            return HttpResponseRedirect(reverse (
             'index'
            ))
        else:
            messages.warning(request,
              "You can't submit a blank form. Please write us a message!"
            )
    else:
        feedback_form = FeedBackForm()
    return render(request, 'polls/feedback.html',
                 {
                  'feedback_form': feedback_form
                 })

# make the list unique
# courtesy https://www.peterbe.com/plog/uniqifiers-benchmark
def make_unique(seq):
    # Not order preserving
    keys = {}
    for e in seq:
        keys[e] = 1
    return keys.keys()

def index(request):
    # Get queryset of quizzes and questions
    # exclude polls with 'draft' and 'suspended' status
    polls = ActivePoll.objects.exclude(single_poll__suspended=True,quiz_poll__suspended=True)\
                          .select_related('single_poll__owner','quiz_poll__owner')
    polls = polls.order_by('-publish')
    #create list of questions and exclude question with 'draft' status
    questions = Question.objects.exclude(
        Q(suspended=True) | Q(publish=None)
    ).order_by('-publish')  # order by most recent
    # # questions = Question.objects.exclude(suspended=True)
    # questions = questions.order_by('-publish')  # order by most recent
    # Display all actions by default
    # initialize the actions when user not logged in
    # actions =""
    # if request.user.is_authenticated():  # incase user is not logged in
    #     actions = Action.objects.all()
    #     following_ids = request.user.following.values_list('id',flat=True) # check if user follow others
    #     # following_ids.append(request.user.id)
    #
    # # if the user follows others, then
    #     if following_ids:
    #         # if user is following others, retrieve only others actions
    #         actions1 = Q(user_id__in=following_ids)
    #         actions2 = Q(user_id=request.user.id)
    #         actions = actions.filter(actions1|actions2)\
    #                          .select_related('user','user__profile')\
    #                          .prefetch_related('target')
    # if request.user.is_authenticated(): # actions when logged in
    #     actions = actions[:8]

    paginator = Paginator(polls, ITEMS_PER_PAGE)  # paging the no of items
    page = request.GET.get('page')
    try:
        polls = paginator.page(page)
    except PageNotAnInteger:
        page = 1
        # if page is not an integer, deliver first page
        polls = paginator.page(1).object_list
    except EmptyPage:
        if request.is_ajax():
            # If the request is AJAX and the page is out of range
            # return an empty page
            return HttpResponse('')
        # If page is out of range deliver last page of results
        polls = paginator.page(paginator.num_pages).object_list

    feed = manager.get_feeds(request.user.id)['aggregated']
    feed2 = MyNotificationFeed(request.user)
    unseen_messages = feed2.count_unseen()
    notification_messages = list(feed2[:10])
    activities2 = list(feed[:200])
    print(activities2)
    # num_view = r.get('poll:19:views')
    # # unpack the returned values in enrich_aggregated_activities
    # aggregated_activities = enrich_aggregated_activities(activities2)

    # The variables to render to the template
    variables = {
       'polls': polls,
       'questions': questions,
       'unseen_messages': unseen_messages,
       # 'feed_acts': enrich_activities(activities),
       'feed_aggr': enrich_aggregated_activities(activities2),
       'short_notification_messages': enrich_aggregated_activities(notification_messages),
       'show_paginator': paginator.num_pages > 1,
       'has_previous': paginator.page(page).has_previous(), # returns True or False
       'has_next': paginator.page(page).has_next(),  # returns True or False
       'page': page,
       'pages': paginator.num_pages,
       'head_title': 'Polls Portal',
       'page_title': 'Welcome to Polls Portal',
       'Welcome_message': 'A place where you can share your views and opinions',
       "show_user": False,
       "show_category":False,
       "date":timezone.now()
    }
    if request.user.is_authenticated():
        if request.is_ajax():
            return render(request, 'polls/question_feed_display.html',variables)

        return render(request, 'polls/index.html', variables)
    else:
        return render(request, 'polls/index_cover.html',variables)

def detail(request, question_id,slug):
    question = get_object_or_404(Question, pk=question_id, slug=slug)
    comments = question.comments.filter(active=True) # filter active comments
    if question.suspended == True:
        messages.info(request,
          "Poll {} you requested has been suspended for violation of our Terms of Use. If you believe this poll was\
          suspended in error, please contact support@pollsportal.com".format(question.id)
        )
        return render(request,'polls/suspended.html',
                {
                "head_title": 'Suspended'
                }
        )

    # increment total image views by 1
    total_views = r.incr('poll:{}:views'.format(question.id))
    # get number of shares received
    total_shares = r.get('question:{}:shares'.format(question.id))

    return render(request, 'polls/detail.html',
                 {
                 'question': question,
                 'comments': comments,
                 'description': question.question_text,
                 'total_views': total_views,
                 'total_shares': total_shares,
                 })

def detail2(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    comments = question.comments.filter(active=True) # filter active comments
    return render(request, 'polls/question_single_ajax.html',
                 {
                 'question': question,
                 'description': question.question_text,
                 'comments': comments,
                 })

# To display results for a particular question
def results(request, question_id, slug):
    question = get_object_or_404(Question, pk=question_id, slug=slug)
    if question.suspended == True:
        messages.info(request,
          "Poll {} you requested has been suspended for violation of our Terms of Use. If you believe this poll has\
          been suspended in error, please contact support@pollsportal.com".format(question.id)
        )
        return render(request,'polls/suspended.html',
                {
                "head_title": 'Suspended'
                }
        )
    tot_votes = (question.total_votes)
    male_votes=0
    female_votes=0
    for choice in question.choice_set.all():
        male_votes += choice.m_votes
        female_votes += choice.f_votes
    # Check if user is superuser
    if not request.user.is_superuser:
        if request.user != question.owner :
            if question.eligibility:
                profile = Profile.objects.get(user=request.user)
                if profile.gender == question.eligible_gender:
                    if not request.user in question.users_voted.all():
                        return render(request,'polls/detail.html',{
                            'question':question,

project/polls/templates/polls/feeds/aggregated_feeds.html
{% load staticfiles %}
{% load extra_tags %}
<!-- A single activity message -->
<div class="aggregated_feeds feed-post">
      {% if aggregated_activity.actor_count == 1 and aggregated_activity.object_ids|length >= 2 %}
          {% with aggregated_activity.last_activity as activity %}
                {% with following=activity.following target_obj=activity.action performer=activity.performer %}
                    {% if aggregated_activity.verb.id == 9 and following != None %}
                        <span><a class="action-performer" position="{{ forloop.counter }}"
                        user_name="{{ performer | escape }}"
                        href="{{performer.get_absolute_url}}">{{performer}}
                        </a>{{aggregated_activity.verb.singular}} <a href="{% url "polls:feeds" %}">
                          {{aggregated_activity.object_ids|length }} </a> people
                        <span><h6>
                            {{ aggregated_activity.updated_at|timesince }} ago</h6></span>
                        </span>
                    {% endif %}
                    {% if aggregated_activity.verb.id != 9 %}
                    <span><a class="action-performer" position="{{ forloop.counter }}"
                    user_name="{{ performer | escape }}"
                    href="{{performer.get_absolute_url}}">{{performer}}
                    </a> {{aggregated_activity.verb.past_tense}} {% if aggregated_activity.verb.id == 5 or aggregated_activity.verb.id == 2 %} on {% endif %}
                      <a href="{% url "polls:feeds" %}">
                        {{aggregated_activity.object_ids|length }}
                      </a> polls
                      <span><h6>
                        {{ aggregated_activity.updated_at|timesince }} ago</h6></span>
                    </span>
                    {% endif %}
                {% endwith %}
          {% endwith %}
      {% elif aggregated_activity.actor_count == 2 and aggregated_activity.object_ids|length == 1 %}
          {% with aggregated_activity.last_activity as activity %}
              {% with following=activity.following target_obj=activity.action performer=activity.performer1 performer2=activity.performer2 %}
                  {% if aggregated_activity.verb.id == 9 and following != None %}
                      <span><a class="action-performer" position="{{ forloop.counter }}"
                      user_name="{{ performer | escape }}" href="{{performer.get_absolute_url}}">{{performer}}</a>
                        and <a class="action-performer" position="{{ forloop.counter }}"
                        user_name="{{ performer2 | escape }}" href="{{performer2.get_absolute_url}}">
                        {{performer2}}</a>
                        <a href="{{following.to_friend.get_absolute_url}}">
                          {% if user == following.to_friend %}you {% else %} {{following.to_friend}} {% endif %}</a>
                        <span><h6>
                          {{ aggregated_activity.updated_at|timesince }} ago</h6></span>
                      </span>
                  {% endif %}
                  {% if aggregated_activity.verb.id != 9%}
                  <span><a class="action-performer" position="{{ forloop.counter }}"
                  user_name="{{ performer | escape }}" href="{{performer.get_absolute_url}}">{{performer}}</a>
                    and <a class="action-performer" position="{{ forloop.counter }}"
                    user_name="{{ performer2 | escape }}" href="{{performer2.get_absolute_url}}">
                    {{performer2}}</a> {{aggregated_activity.verb.past_tense}}
                    {% if aggregated_activity.verb.id == 5 or aggregated_activity.verb.id == 2 %} on {% endif %}
                    <a href="{{target_obj.get_absolute_url}}">{{target_obj}}</a>
                    <span><h6>
                      {{ aggregated_activity.updated_at|timesince }} ago</h6></span>
                  </span>
                  {% endif %}
              {% endwith %}
          {% endwith %}
      {% elif aggregated_activity.actor_count > 2 and aggregated_activity.object_ids|length == 1 %}
          {% with aggregated_activity.last_activity as activity %}
              {% with following=activity.following target_obj=activity.action performer=activity.performer %}
                  {% if aggregated_activity.verb.id == 9 and following != None %}
                      <span><a class="action-performer" position="{{ forloop.counter }}"
                      user_name="{{ performer | escape }}" href="{{performer.get_absolute_url}}">{{performer}}</a>
                         and {{aggregated_activity.other_actor_count}}
                        others {{aggregated_activity.verb.plural}}
                        <a href="{{following.to_friend.get_absolute_url}}">
                          {% if user == following.to_friend %}you {% else %} {{following.to_friend}} {% endif %}</a>
                        <span><h6>
                          {{ aggregated_activity.updated_at|timesince }} ago</h6></span>
                      </span>
                  {% endif %}
                  {% if aggregated_activity.verb.id != 9%}
                      <span><a class="action-performer" position="{{ forloop.counter }}"
                      user_name="{{ performer | escape }}" href="{{performer.get_absolute_url}}">{{performer}}</a>
                         and {{aggregated_activity.other_actor_count}}
                        others {{aggregated_activity.verb.past_tense}}
                        {% if aggregated_activity.verb.id == 5 or aggregated_activity.verb.id == 2 %} on {% endif %}
                        <a href="{{target_obj.get_absolute_url}}">{{target_obj}}</a>
                        <span><h6>
                          {{ aggregated_activity.updated_at|timesince }} ago</h6></span>
                      </span>
                  {% endif %}
              {% endwith %}
          {% endwith %}
      {% elif aggregated_activity.actor_count == 1 and aggregated_activity.object_ids|length == 1 %}
          {% with aggregated_activity.last_activity as activity %}
              {% with following=activity.following target_obj=activity.action performer=activity.performer %}
                  {% if aggregated_activity.verb.id == 9 and following != None %}
                      <span><a class="action-performer" position="{{ forloop.counter }}"
                      user_name="{{ performer | escape }}" href="{{performer.get_absolute_url}}">
                      {{performer}}</a> {{aggregated_activity.verb.singular}}
                      <a href="{{following.to_friend.get_absolute_url}}">
                          {% if user == following.to_friend %} you {% else %} {{following.to_friend}} {% endif %}</a>
                      <span><h6>
                        {{ aggregated_activity.updated_at|timesince }} ago</h6></span>
                      </span>
                  {% endif %}
                  {% if aggregated_activity.verb.id != 9 %}
                      <span><a class="action-performer" position="{{ forloop.counter }}"
                      user_name="{{ performer | escape }}" href="{{performer.get_absolute_url}}">
                      {{performer}}</a> {{aggregated_activity.verb.past_tense}}
                      {% if aggregated_activity.verb.id == 5 or aggregated_activity.verb.id == 2 %} on {% endif %}
                      <a href="{{target_obj.get_absolute_url}}">{{target_obj}}</a>
                      <span><h6>
                      {{ aggregated_activity.updated_at|timesince }} ago</h6></span>
                      </span>
                  {% endif %}
              {% endwith %}
          {% endwith %}

      {% else %}
          {% for activity in aggregated_activity.last_activities %}
                {% with following=activity.following target_obj=activity.action performer=activity.performer %}
                {% myactors_count activity.performer_grp performer.id as performer_count %}
                  {% if forloop.last %}
                    {% for actor in activity.performers_obj_list %}
                      {% myactors_count activity.performer_grp actor.id as performer_count %}
                          {% if performer_count >= 2 %}
                              {% if aggregated_activity.verb.id != 9 %}
                                  <span><a class="action-performer" position="{{ forloop.counter }}"
                                  user_name="{{ actor | escape }}" href="{{actor.get_absolute_url}}">
                                  {{actor}}</a> {{aggregated_activity.verb.past_tense}}
                                  {% if aggregated_activity.verb.id == 5 or aggregated_activity.verb.id == 2 %} on {% endif %}
                                    <a href="{% url "polls:feeds" %}">
                                      {{performer_count }}
                                    </a> polls
                                    <span>
                                      <h6>{{ aggregated_activity.updated_at|timesince }} ago</h6></span>
                                  </span>
                              {% endif %}
                          {% endif %}
                    {% endfor %}
                  {% endif %}

                  {% if performer_count == 1 %}
                      {% if aggregated_activity.verb.id == 9 and following != None %}
                          <span><a class="action-performer" position="{{ forloop.counter }}"
                          user_name="{{ performer | escape }}" href="{{performer.get_absolute_url}}">
                          {{performer}}</a> {{aggregated_activity.verb.singular}}
                          <a href="{{following.to_friend.get_absolute_url}}">
                          {% if user == following.to_friend %} you {% else %} {{following.to_friend}} {% endif %}</a>
                            <span>
                              <h6>{{ aggregated_activity.updated_at|timesince }} ago</h6></span>
                          </span>
                      {% endif %}
                      {% if aggregated_activity.verb.id != 9 %}
                          <span><a class="action-performer" position="{{ forloop.counter }}"
                          user_name="{{ performer | escape }}" href="{{performer.get_absolute_url}}">
                          {{performer}}</a> {{aggregated_activity.verb.past_tense}}
                          {% if aggregated_activity.verb.id == 5 or aggregated_activity.verb.id == 2 %} on {% endif %}
                            <a href="{{target_obj.get_absolute_url}}">{{target_obj}}</a>
                            <span><h6>{{ aggregated_activity.updated_at|timesince }} ago</h6></span>
                          </span>
                      {% endif%}
                  {% endif %}

                {% endwith %}
          {% endfor %}
      {% endif %}

</div>

project/polls/templates/polls/feeds/normal_feeds.html
{% extends "polls/base.html" %}
{% load staticfiles %}
{% block title %} PollsPortal | Activity Feeds {% endblock %}
{% block head %}  What's happening {% endblock %}
{% block external %}
{% endblock %}
{% block content %}
<ul>
    {% for a in feed_actions %}
       <li>
          {% with following=a.following performer=a.actor target_obj=a.action profile=a.actor.profile %}
            <div class="action">
              <div class="info">
                  {% if a.verb.id == 9 and following != None %}
                      <span><a href="{{performer.get_absolute_url}}">{{performer}}</a>
                        {{a.verb.singular}} <a href="{{following.to_friend.get_absolute_url}}">
                          {% if user == following.to_friend %}you {% else %} {{following.to_friend}} {% endif %}</a>
                          <span><h6>{{ a.time|timesince }} ago</h6></span>
                      </span>
                  {% endif %}
                  {% if a.verb.id != 9 %}
                  <span><a href="{{performer.get_absolute_url}}">{{performer}}</a>
                    {{a.verb.past_tense}} {% if a.verb.id == 5 or a.verb.id == 2 %} on {% endif %}
                    <a href="{{target_obj.get_absolute_url}}">
                        {{target_obj }}</a><span><h6>
                      {{ a.time|timesince }} ago</h6></span>
                  </span>
                  {% endif %}

              </div>
            </div>
          {% endwith %}
        </li>
    {% endfor %}
</ul>
{% endblock %}