config/urls.py
from django.conf.urls import url, include, handler404, handler500
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from project.polls import views
# import the verbs to ensure it is registered
from project.polls.verbs import Vote, Like, Share, UpdateProfile, FollowVerb

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('project.polls.urls',namespace='polls',
        app_name='polls')),
    url(r'^account/', include('project.account.urls', namespace='account',
        app_name='account')),
    url(r'^$', views.index, name='index'), # homepage
    # url(r'^index_graph/$', views.index_graph, name='index_graph'),
    url(r'^privacy-policy/$', views.privacy_policy, name='privacy'),
    url(r'^terms-of-service/$', views.terms_of_service, name='terms'),
    url(r'^help-using-our-services/$', views.help_page, name='help'),
    url(r'^feedback/$', views.feedback_page, name="feedback"),

    #Add social URL
    url(r'^social-auth/', include('social_django.urls', namespace='social')),
]

handler404 = views.error_404
handler500 = views.error_500

project/polls/urls.py
from django.conf.urls import url, include
from project.polls import views

app_name='polls'
urlpatterns = [
    #Browsing
    # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/(?P<slug>[-\w]+)/$',
        views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/(?P<slug>[-\w]+)/results/$',
        views.results, name='results'),
    url(r'^feat/$', views.features, name='features'),
    url(r'^popular/$', views.popular_polls, name='popular'),
    url(r'^recent/$', views.recent_polls, name='recent'),
    url(r'^search/$', views.search_page, name='search'),
    url(r'^list-voters/$', views.get_voters_list, name='voters'),
    url(r'^graphs/$', views.dashboard_graphs, name="graphs"),
    url(r'^([-\w]+)/voted/$', views.voted_polls, name='voted_polls'),
    url(r'^([-\w]+)/liked/$', views.liked_polls, name='liked_polls'),
    url(r'^([-\w]+)/commented/$', views.commented_polls, name='commented_polls'),

    # content management
    url(r'^question/(?P<question_id>[0-9]+)/settings/(?P<poll_type>[-\w]+)/$',
        views.question_settings, name='questionsettings'),
    url(r'remove/poll/(?P<question_id>[0-9]+)/$', views.suspend_poll, name='suspend'),
    url(r'^comments/(?P<question_id>[0-9]+)/$', views.comments, name='comments'),
    # ex: /polls/5/vote/
    url(r'^vote/(?P<question_id>[0-9]+)/$', views.vote, name='vote'),
    url(r'^dashboard/user/([-\w]+)/$', views.dashboard, name='dashboard'),
    url(r'^user/([-\w]+)/$', views.user_page, name='user_page'),
    url(r'^([-\w]+)/save/$', views.question_save, name='save_page'),
    url(r'^edit/(?P<question_id>[0-9]+)/save/$', views.question_edit,
        name='edit_question'),
    url(r'^submit_a_poll/$',views.create_anonymous, name='create'),
    url(r'^like/(?P<question_id>[0-9]+)/$', views.like, name="like"),
    url(r'^new-share/(?P<question_id>[0-9]+)/(?P<poll_type>[-\w]+)/$',
        views.share, name="share"),
    url(r'^share/ranking/$', views.share_ranking, name="share_ranks"),

    # quiz Browsing
    url(r'^quiz/(?P<quiz_id>[0-9]+)/(?P<slug>[-\w]+)/$', views.quiz_detail,
        name='quiz_detail'),
    # quiz content management
    url(r'^([-\w]+)/quiz/presave/$', views.pre_create_quiz, name='pre_save_quiz'),
    url(r'^create/(?P<quiz_id>[0-9]+)/quiz/save/$', views.create_new_quiz,
        name='save_quiz'),
    url(r'^edit/(?P<quiz_id>[0-9]+)/quiz/$', views.edit_quiz, name='edit_quiz'),
    url(r'^quiz_question/edit/(?P<question_id>[0-9]+)/quiz/$',
        views.edit_quiz_question, name='edit_quiz_question'),
    url(r'^quiz_vote/(?P<quiz_id>[0-9]+)/(?P<slug>[-\w]+)/$', views.quiz_vote,
        name='quiz_vote'),

    # Friends
    url(r'^friends/([-\w]+)/$', views.friends_page, name='friends'),
    url(r'^friend/follow/$', views.friend_follow, name='friend_follow'),
    url(r'^friend/invite/$', views.friend_invite, name='friend_invite'),
    url(r'^friend/accept/([-\w]+)/$', views.friend_accept, name='friend_accept'),

    # mail
    url(r'^send_mail/$', views.send_bulk, name='sendmail'),
    url(r'^personal_mail/$', views.one_message, name='personalmail'),

    # feeds management
    url(r'^news_feed/$', views.feeds, name='feeds'),
    url(r'^feed/notifications/$', views.notification, name='notification'),
    url(r'^seen_activity/$', views.mark_as_seen,),

    url(r'^question/(?P<question_id>[0-9]+)/$', views.detail2, name='detail2'),
]

project/polls/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from datetime import datetime, timedelta, date
from django.core.urlresolvers import reverse # use for get_absolute_url
from django.template.defaultfilters import slugify
from django.core.exceptions import ValidationError
# Adding generic relations to modelse
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.fields import GenericRelation
from channels.binding.websockets import WebsocketBinding
# Create your models here.
class Quiz(models.Model):
    MODE = (
      ('notTimed','self-paced'),
      ('timed','set time')
    )
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    poll_type = models.CharField(max_length=15,default='Quiz')
    slug = models.SlugField(max_length=220,db_index=True,unique=True)
    mode = models.CharField(max_length=15,choices=MODE,default='notTimed')
    quiz_duration = models.PositiveIntegerField(null=True,blank=True)
    attempt = models.PositiveIntegerField(db_index=True,default=3)
    quiz_takers = models.ManyToManyField(settings.AUTH_USER_MODEL,through='QuizTakerScore',
                                         related_name='quiztakers')
    total_likes = models.PositiveIntegerField(db_index=True,default=0)
    user_liked = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='quizlikes')
    users_share= models.ManyToManyField(settings.AUTH_USER_MODEL,blank=True, related_name='quizsharers')
    publish = models.DateTimeField(null=True,blank=True)
    created = models.DateTimeField(auto_now_add=True)
    suspended = models.BooleanField(default=False)
    lock_date = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=22,default='Draft')
    # settings = GenericRelation(PollSettings,content_type_field='content_type',
    #                     object_id_field='object_id',related_query_name='quizzes')

    class Meta:
        verbose_name_plural = "Quizzes" # To display plural of category

    def __str__(self):
        return "{}".format(self.title)

    def get_status(self):
        # determine status of quiz
        if self.suspended:
            status = "Suspended"
        elif self.publish is None or self.publish <= self.created:
            status = "Draft"
        elif self.publish > timezone.now():
            status = "Pending"
        elif self.lock_date <= timezone.now():
            status = "Closed"
        elif self.publish <= timezone.now():
            status = "Active"
        return status

    def get_absolute_url(self):
        return reverse('polls:quiz_detail', args=[self.id,self.slug])

    def create_activity(self, performer,verb,timenow):
        from stream_framework.activity import Activity
        # from polls.verbs import Like as LikeVerb
        from django.utils.timezone import make_naive
        import pytz
        activity = Activity(
            performer.id,
            verb,
            self.id,
            self.owner_id,
            time=make_naive(timenow, pytz.utc)
        )
        return activity

    def save(self,*args,**kwargs):
        # determine status of quiz
        if self.suspended:
            self.status = "Suspended"
        elif self.publish is None or self.publish <= self.created:
            self.status = "Draft"
        elif self.publish > timezone.now():
            self.status = "Pending"
        elif self.lock_date <= timezone.now():
            self.status = "Closed"
        elif self.publish <= timezone.now():
            self.status = "Active"
        if not self.id:
            self.slug = slugify(self.title)
        super(Quiz,self).save(*args,**kwargs)


class OpenAnswer(models.Model):
    answer = models.CharField(max_length=60)

    def __str__(self):
        return self.answer


class QuizQuestion(models.Model):
    MODE = (
      ('choice','Multiple choice'),
      ('open','open-ended')
    )
    quiz = models.ForeignKey(Quiz,on_delete=models.CASCADE)
    quiz_question_text = models.CharField(max_length=160)
    question_type = models.CharField(max_length=18,choices=MODE,default='choice')
    participants = models.ManyToManyField(settings.AUTH_USER_MODEL,blank=True)
    open_answer = models.OneToOneField(OpenAnswer,null=True,blank=True,
                                        on_delete=models.CASCADE)

    def __str__(self):
        return "{}".format(self.quiz_question_text)


class QuizChoice(models.Model):
    quiz_question = models.ForeignKey(QuizQuestion, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=160)
    answer = models.BooleanField(default=False)

    def __str__(self):
        return "{}".format(self.choice_text)


class SubmittedOpenAnswer(models.Model):
    quiz_question = models.ForeignKey(QuizQuestion, on_delete=models.CASCADE)
    answerer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    submitted_answer = models.CharField(max_length=60)

    def __str__(self):
        return "{}".format(self.submitted_answer)


class QuizTakerScore(models.Model):
    quiz_taker = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    score = models.PositiveIntegerField(db_index=True,default=0)
    number_of_attempt = models.PositiveIntegerField(db_index=True,default=0)
    choice_answers = models.ManyToManyField(QuizChoice,blank=True,
                                              related_name="selectedanswers")
    open_answers = models.ManyToManyField(SubmittedOpenAnswer,blank=True,
                                       related_name='writtenanswers')
    date_answered = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return "score: {}".format(self.score)


class Question(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,null=True)
    question_text = models.CharField(max_length=160)
    poll_type = models.CharField(max_length=16,default='Opinion')
    # remove unique=True from slug field to allow flexibility
    slug = models.SlugField(max_length=200,db_index=True)  # unique=True removed
    category = models.CharField(max_length=22,default='General')
    total_votes = models.PositiveIntegerField(db_index=True,default=0)
    anonymous_votes = models.PositiveIntegerField(default=0,blank=True,null=True)
    users_voted= models.ManyToManyField(settings.AUTH_USER_MODEL,blank=True, related_name='voters')
    users_share= models.ManyToManyField(settings.AUTH_USER_MODEL,blank=True, related_name='sharers')
    publish = models.DateTimeField(null=True,blank=True)
    created = models.DateTimeField(auto_now_add=True)
    poll_info = models.CharField(max_length=200,null=True,blank=True)
    eligibility=models.BooleanField(default=False)
    eligible_gender = models.CharField(max_length=10,null=True,blank=True)
    suspended = models.BooleanField(default=False)
    lock_date = models.DateTimeField(default=timezone.now)
    total_likes = models.PositiveIntegerField(db_index=True,default=0)
    user_liked = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='likes')
    quota = models.PositiveIntegerField(null=True,blank=True)
    status = models.CharField(max_length=22,default='Draft')
    

    def __str__(self):
        return "{}".format(self.question_text)

    def was_published_recently(self):
        return self.publish >= timezone.now() - timedelta(days=1)

    def get_status(self):
        """Set the status of each poll according to publish date"""
        if self.suspended:
            return "Suspended"
        elif self.publish is None or self.publish <= self.created:
            return "Draft"
        elif self.publish >= timezone.now():
            return "Pending"
        elif self.quota == self.total_votes or self.lock_date <= timezone.now():
            return "Closed"
        elif self.publish <= timezone.now():
            return "Active"
        return self.status

    def get_absolute_url(self):
        return reverse('polls:detail', args=[self.id,self.slug])

    def save(self,*args,**kwargs):
        # determine the status of poll
        if self.suspended:
            self.status = "Suspended"
        elif self.publish is None or self.publish <= self.created:
            self.status = "Draft"
        elif self.publish > timezone.now():
            self.status = "Pending"
        elif self.quota == self.total_votes or self.lock_date <= timezone.now():
            self.status = "Closed"
        elif self.publish <= timezone.now():
            self.status = "Active"
        if not self.id:
            self.slug = slugify(self.question_text)
        result = super(Question,self).save(*args,**kwargs)
        return result

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=160)
    votes=models.IntegerField(default=0)
    m_votes=models.IntegerField(default=0)
    f_votes=models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

class ActivePoll(models.Model):
    poll_type = models.CharField(max_length=15)
    poll_title = models.CharField(max_length=200)
    publish = models.DateTimeField(null=True,blank=True)
    quiz_poll = models.ForeignKey(Quiz, null=True, blank=True, on_delete=models.CASCADE)
    single_poll = models.ForeignKey(Question, null=True, blank=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "ActivePolls"

    def __str__(self):
        return "{}".format(self.poll_title)

    def get_absolute_url(self):
        if self.single_poll != None and self.quiz_poll is None:
            return reverse('polls:detail', args=[self.single_poll.id,self.single_poll.slug])

project/polls/templates/polls/bulk_mail_form.html
{% extends "polls/base.html" %}
{% block title %}Send mail{% endblock %}
{% block head %}<div class="page-header">Bulk email</div>{% endblock %}
{% block content %}

<form method="post" action=".">
  {{ form.as_p }}
  {% csrf_token %}
  <input class="btn btn-success" type="submit" value="send message" />
</form>
{% endblock %}

project/polls/templates/polls/comments.html
{% load staticfiles %}
{% if question %}
    <div>
      <h3>
        {{question.question_text}}
      </h3>
    </div>
    <div>
      <div class="fb-comments" data-href="https://www.pollsportal.com/polls/{{ question.id }}/{{question.slug}}/results" data-width="380" data-numposts="5"></div>
    </div>
    {% with question.comments.count as total_comments %}
      <h4>{{ total_comments }} comment{{total_comments|pluralize}}</h4>
    {% endwith %}
    {% for comment in question.comments.all %}
    <div class='comment'>
      <p class="info"><em>
        <strong>{{ comment.name }}</strong> on
        {{ comment.created }}</em>
      </p>
      {{ comment.body|linebreaks }}
    </div>
    {% empty %}
      <p>There are no comment yet for this poll.</p>
    {% endfor %}
    {% if new_comment %}
      <h3>Your comment has been added.</h3>
    {% else %}

      <div class="pull-right">
        <a class="question-link" href="{% url "polls:detail2" question.id %}">back</a>
      </div>
      <div class="form-group comment-box">
        <form action="{% url "polls:comments" question.id %}" method="post">
          <!-- <p><label for ="id_body">comment:</label></p> -->
          <p><textarea class="form-control" cols ="30" id="id_body" name="body" rows="2"></textarea></p>
          {% csrf_token %}
          <p><input id="submitcomment" questionid={{question.id}} class="btn btn-primary" type='submit' value="Add comment"></p>
        </form>
      </div><!-- comment-box -->
    {% endif %}
{% endif %}

project/polls/templates/polls/comments_list.html
{% extends 'polls/base.html' %}
{% block title %}Polls commented{% endblock %}
{% block head %}<div class="page-header">{{username}} commented on </div>{% endblock %}
{% block content %}

{% include "polls/questions_list.html" %}

{% endblock %}

project/polls/templates/polls/detail.html
{% extends 'polls/base.html' %}
{% load staticfiles %}
{% load extra_tags %}
{% block title %}{{question.question_text|capitalize}}{% endblock %}
{% block external %}
  <script type="text/javascript" src="{% static "polls/js/dashboard.js" %}"></script>
  <script type="text/javascript" src="{% static "polls/js/quiz_display.js" %}"></script>
{% endblock %}
{% block content %}
  {% if question %}
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <span class="badge">
          <span class="total">{{ total_views }}</span>
          view{{ total_views|pluralize }}
        </span>
        {% if total_shares != None %}
        |
          <span class="badge">
            <span class="total">{{ total_shares }}</span>
            share{{ total_shares|pluralize }}
          </span>
        {% endif %}
      </div>
    </div>
    <div class="row">
      <div class="col-md-8 col-md-offset-1">
        <h2 class="page-header">{{question.question_text | capitalize }}
          {% if question.status == 'Draft' %}
            <span class="status-draft"><i class="fa fa-file-o"></i>
            </span>
          {% elif question.status == 'Active' %}
            <span class="status-active"><i class="fa fa-check-circle"></i>
              </span>
          {% elif question.status == 'Closed' %}
            <span class="status-locked"><i class="fa fa-lock"></i>
              </span>
          {% elif question.status == 'Suspended' %}
            <span class="status-suspend"><i class="fa fa-times"></i>
              </span>
          {% elif question.status == 'Pending' %}
            <span class="status-pending"><i class="fa fa-unlock"></i>
              </span>
          {% endif %}
        </h2>

        <div class="form-options">

          <form action='{% url 'polls:vote' question.id %}' method='post'>
            {% csrf_token %}
            {% for choice in question.choice_set.all %}
            <div class="form-group">
                <input type='radio' name='choice' id='choice{{ forloop.counter }}'
                    value="{{ choice.id}}" />
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text | capitalize | escape }}</label>
            </div>
            <div class="divider"></div>

            {% endfor %}
            <button class="btn btn-md btn-success form-control" type="submit" value="Vote"> Vote </button>
          </form>
        </div>
      </div>

      <div class="col-md-3">
        <div class="panel panel-info">
          <div class="panel-heading">
            {% with comments.count as total_comments %}
              <h4>{{ total_comments }} comment{{total_comments|pluralize}}</h4>
            {% endwith %}
          </div>
          {% for comment in comments %}
          <div class='panel-body comment'>
            <p class="info"><em>
              <strong>{{ comment.name }}</strong> |
              {{ comment.created }}</em>
            </p>
            {{ comment.body|linebreaks }}
          </div>
          {% empty %}
            <p>There are no comments for this poll.</p>
          {% endfor%}
        </div>

      </div><!--col-md-3-->

    </div>
  </div>
  {% endif %}

  {% if quiz %}
    <div class="row">
      <div class="col-md-4">
        {% if total_shares != None %}
        |
          <span class="badge">
            <span class="total">{{ total_shares }}</span>
            share{{ total_shares|pluralize }}
          </span>
        {% endif %}
      </div>
    </div>
    {% if show_result %}
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <h2 class="page-header">{{ quiz | capitalize }}
          </h2>
          <div class="quiz-result">
            <ol>
            {% for question in quiz.quizquestion_set.all %}
              <li>{{ question }}
                {% if question.question_type == "choice" %}
                <ul>
                  {% for choice in question.quizchoice_set.all %}
                    <li><h5>{{choice}}
                      <span><!-- logic to show user's chosen answer -->
                        {% if choice.answer %}
                          {% if choice in choice_answers%}
                            <i class="fa fa-check"></i>
                          {% endif %}
                        {% else %}
                          {% if choice in choice_answers %}
                          <i class="fa fa-times"></i>
                          {% endif %}
                        {% endif %}
                      </span>
                      </h5>
                    </li>
                  {% endfor %}
                </ul>
                {% else %}
                  {% for answer in open_answers %}
                    {% if answer.quiz_question == question %}
                      {{ answer }} <span>
                        {% if answer.submitted_answer == question.open_answer.answer %}
                          <i class="fa fa-check"></i>
                        {% else %}
                          <i class="fa fa-times"></i>
                        {% endif %}
                      </span>
                    {% endif %}
                  {% endfor %}
                {% endif %}
              </li>
            {% endfor %}
            </ol>
          </div>
        </div>
      </div>
    </div>
    {% elif messages %}
    <div class="alert alert-dismissable" role='alert'>
      <button type="button" class="close" data-dismiss="alert"
        aria-hidden="true">&times;</button>
      <ul class="messages alert-{{message.tags}}">
        {% for message in messages %}
          <li class="alert alert-{{message.tags}} alert-dismissable">
            {{ message }}</li>
        {% endfor %}
      </ul>
    </div>
    {% else %}
    <div class="container target">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <h2 class="page-header">{{ quiz | capitalize }}
          </h2>
          {% if quiz.mode == "timed" %}
          <p class="quiz-time">
            You have {{quiz.attempt|subtract:number_of_attempt}} attempt{{quiz.attempt|subtract:number_of_attempt|pluralize}} left
            <span class="pull-right">Duration: <span class="quiz-time">{{quiz.quiz_duration}} minute{{quiz.quiz_duration|pluralize}}</span>
            </span>
          </p>

          <div class="instructions">
            <h4><strong>Instructions:</strong></h4>
            <p>Read the following instructions carefully.</p>
            <ol>
              <li>This quiz will take <strong>{{quiz.quiz_duration}} minute{{quiz.quiz_duration|pluralize}}</strong></li>
              <li>Ensure you answer all questions before submitting</li>
              <li>The current question is highlighted among the questions number above the
                and you can answer the questions in any order </li>
              <li>Once you click start, a timer will be shown at left-top of the page
                and your number of attempt will be updated immediately </li>
              <li><strong>Do not</strong> refresh the page once the timer start for the number of attempt will be
                increased</li>
              <li>Number of allowed attempts: {{quiz.attempt}}</li>
            </ol>

          </div>
          <div class="start-button">
            <div id="id_start_quiz" url="{% url "polls:quiz_detail" quiz.id quiz.slug %}" class="btn btn-sm btn-default"> Start Quiz </div>
          </div>
          {% endif %}

          <div mode="{{quiz.mode}}" class="form-options paginated">
            <script>
              var formSection = document.getElementsByClassName('form-options')
              if($(formSection).attr('mode') === 'timed'){
                $(formSection).hide()
              }
            </script>
            <div class="clearfix"></div>
            <form id="submit-quiz" action="{% url "polls:quiz_vote" quiz.id quiz.slug %}" method='post'>
              {% csrf_token %}
              <ul>
              {% for question in quiz.quizquestion_set.all %}
                <div class="section">
                  <div><h4>{{ question }}</h4>
                    {% if question.question_type == "choice" %}

                      {% for choice in question.quizchoice_set.all %}
                      <div class="choices-list">
                        <input type='radio' name='question_choice{{question.id}}' id='id_question_choice{{question.id}}'
                            value="{{choice.id}}" />
                        <label for="id_question_choice{{question.id}}">{{ choice.choice_text | capitalize | escape }}</label>
                      </div>
                      {% endfor %}
                    {% else %}
                    <div class="choices-list">
                      <input type='text' name='question_answer{{question.id}}'
                         id='id_question_answer{{question.id}}'/>
                    </div>
                    {% endif %}
                  </div>
                </div><!-- section -->
              {% endfor %}
              </ul>
              <button class="sr-only btn btn-sm btn-primary" type="submit" value="submit"> Submit </button>
            </form>
          </div><!-- form-options -->
        </div>
      </div><!-- row-->
    </div><!-- container -->
  {% endif %}
{% endif %}
<script>

</script>
{% endblock %}

project/polls/templates/polls/quiz_form_ajax.html
{% load staticfiles %}

<script type="text/javascript" src="{% static "polls/js/quizform.js" %}"></script>
<script type="text/javascript" src="{% static "polls/js/quizform_styling.js" %}"></script>

{% if quiz_form %}
  <form class="new-quiz" method ="post" action ="{% url "polls:pre_save_quiz" user.username %}">
    {% csrf_token %}
    <fieldset>
      <legend>Basic Quiz Info</legend>
      <div class="quiz-title-edit">
        {{ quiz_form.as_p }}
      </div>
    </fieldset>
    <input type="submit" value="Create new quiz"/>
  </form>
{% endif %}

<div class="row main-target">
  {% if quiz %}
  <div class="col-md-4 col-md-push-8 target">
    <div class="panel panel-green">
      <div class="panel-heading">
        Quiz title: {{quiz}}
      </div><!-- panel-heading-->
      <div class="panel-body">
        <div class="quiz-details">
            {% if quiz.quizquestion_set.all.count > 0 %}
              <ol>
                {% for question in quiz.quizquestion_set.all %}
                <div class="section">
                  <li><h4>{{ question }}</h4>
                    {% if question.question_type == 'open' %}
                      <p class="small">
                        <strong>Answer:</strong><h5>{{ question.open_answer }}</h5>
                      </p>
                    {% else %}
                    <ul>
                      {% for choice in question.quizchoice_set.all %}
                        <li><h5>{{choice}}
                          <span>{% if choice.answer %}<i class="fa fa-check">{% endif %}</i>
                          </span>
                          </h5>
                        </li>
                      {% endfor %}
                    </ul>
                    {% endif %}
                    <a class="edit-question small" href="{% url "polls:edit_quiz_question" question.id %}">edit</a>
                  </li>
                </div>
                {% endfor %}
              </ol>
            {% else %}
              You have not saved any quiz question
            {% endif %}
        </div>
      </div><!-- panel-body-->
    </div><!-- panel-green -->
  </div><!--col-md-6-->
  {% endif %}

  <div class="clearfix visible-xs"></div>

  <div class="col-md-5 col-md-pull-3">
    <div class="main-quiz-form-container">
    {% if edit %}
      <form id="edit-quiz" method="post" action ="{% url "polls:edit_quiz" quiz.id %}">
        {% csrf_token %}
        <p class="hidden duration-value" duration="{{quiz.quiz_duration}}"></p>
        <fieldset>
          <legend>Basic Quiz Info</legend>
          <div class="quiz-title-edit">
            {{ quiz_edit_form.as_p }}
          </div>
        </fieldset>

        {{ question_formset.management_form }}
        {% for question,form,choice_formset in formset %}
        <fieldset>
          <legend>Quiz Question</legend>
          <div class="page-header section">
            {{ form.as_p }}
            <p class="answer-item">
              <label for="id_open_answer">provide an answer:</label>
              <input type="text" name="quizquestions-open_answer{{question.id}}" value="{{question.open_answer}}" id="id_open_answer" />
            </p>
            {{ choice_formset.management_form }}
            {% for choice in choice_formset %}
            <div class="item">
              {{ choice.as_p }}
            </div>
            {% endfor %}
          </div>
        </fieldset>
        {% endfor %}
        <input type="submit" name="submit" value="save changes"/>
        <span>
          <a id="save-continue" class="btn btn-default">Save and Add more questions</a>
        </span>
      </form>
    {% elif formset %}
      <div class="question-box">
        <form id="add-quiz-question" method ="post" action ="{% url "polls:save_quiz" quiz.id %}">
          {% csrf_token %}
          {{ question_formset.management_form }}
          {% for form,choice_formset in formset %}
          <fieldset>
            <legend>Question</legend>
            <div class="section">
            {{ form.as_p }}
            {{ choice_formset.management_form }}
            {% for choice in choice_formset %}
            <div class="item">
              {{ choice.as_p }}
              <p style=""><a prefix="" class="delete" href="#">remove</a></p>
            </div>
            {% endfor %}
            <button id="add-option" prefix="" type="button" class="btn btn-primary btn-xs">Add option</button>
            </div>
          </fieldset>
          {% endfor %}
          <input class="add-question" type="submit" name="add" value="add question"/>
        </form>
      </div><!-- question-box -->
    {% endif %}
    </div><!-- main-quiz-form-container -->
  </div><!-- col-md-6-->
</div>

project/polls/templates/polls/recent_polls_ajax.html
<div id="recent">
  <h2>Recent polls</h2>
  <p> These are polls created less than 48hrs ago</p>
  {% include "polls/questions_list.html" %}
  {% if more_view %}
  <div class='row'>
    <a class="btn btn-primary" href="{% url "polls:recent" %}">more</a>
  </div>
  {% endif %}
</div>